# Package Import

In [1]:
pip install FinRatioAnalysis

Collecting FinRatioAnalysis
  Downloading FinRatioAnalysis-0.0.7-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: yfinance in /usr/local/lib/python3.10/dist-packages (from FinRatioAnalysis) (0.2.51)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from FinRatioAnalysis) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from FinRatioAnalysis) (2.2.2)
Requirement already satisfied: pandas-datareader in /usr/local/lib/python3.10/dist-packages (from FinRatioAnalysis) (0.10.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from FinRatioAnalysis) (5.24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->FinRatioAnalysis) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->FinRatioAnalysis) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->FinRatioAnalysis) (2024.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from pandas-datareader->FinRatioAnalysis) (5.3.0)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from pandas-datareader->FinRatioAnalysis) (2.32.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->FinRatioAnalysis) (9.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly->FinRatioAnalysis) (24.2)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.10/dist-packages (from yfinance->FinRatioAnalysis) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from yfinance->FinRatioAnalysis) (4.3.6)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.10/dist-packages (from yfinance->FinRatioAnalysis) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.10/dist-packages (from yfinance->FinRatioAnalysis) (3.17.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.10/dist-packages (from yfinance->FinRatioAnalysis) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from yfinance->FinRatioAnalysis) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4>=4.11.1->yfinance->FinRatioAnalysis) (2.6)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance->FinRatioAnalysis) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance->FinRatioAnalysis) (0.5.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pandas-datareader->FinRatioAnalysis) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pandas-datareader->FinRatioAnalysis) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pandas-datareader->FinRatioAnalysis) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pandas-datareader->FinRatioAnalysis) (2024.12.14)
Downloading FinRatioAnalysis-0.0.7-py3-none-any.whl (5.8 kB)
Installing collected packages: FinRatioAnalysis
Successfully installed FinRatioAnalysis-0.0.7

In [2]:
import yfinance as yf
import pandas as pd
import numpy as np
import pandas_datareader as pdr
import plotly.graph_objects as go
import datetime as dt
from FinRatioAnalysis import FinRatioAnalysis

In [3]:
tickers = ['IBM', 'AAPL', 'GOOG']

In [4]:
objetos = {}

for ticker in tickers:
    obj = FinRatioAnalysis(ticker, 'yearly')
    objetos[ticker] = obj

# Ahora objetos es un diccionario con claves 'IBM', 'AAPL' y 'GOOG' y valores que son objetos de la clase FinRatioAnalysis

# Acceder al objeto para el ticker 'IBM'
obj_ibm = objetos['IBM']

# Acceder al objeto para el ticker 'AAPL'
obj_aapl = objetos['AAPL']

# Acceder al objeto para el ticker 'GOOG'
obj_goog = objetos['GOOG']

In [5]:
obj_ibm.ReturnRatios()

                 ROE       ROA      ROCE GrossMargin OperatingMargin NetProfit
2023-12-31  0.332934  0.055471  0.101831    0.554478        0.166457  0.121274
2022-12-31  0.074736  0.012889  0.024776    0.540013        0.039187  0.027094
2021-12-31  0.303793    0.0435  0.060905    0.549005        0.104479   0.10012
2020-12-31  0.271399   0.03584  0.033247    0.559361        0.069954  0.101307

In [6]:
obj_ibm.EfficiencyRatios()

,AssetTurnover,ReceivableTurnover,InventoryTurnover,FixedAssetTurnover
2023-12-31,0.457406,4.432502,23.738157,0.604497
2022-12-31,0.475704,4.259976,17.939433,0.616866
2021-12-31,0.434474,3.829272,15.685264,0.559729
2020-12-31,0.353777,3.24697,13.418322,0.472399

In [7]:
obj_ibm.LiquidityRatios()

,CurrentRatios,QuickRatio,CashRatio,DIR,TIE,TIE_CB,CAPEX_OpCash,OpCashFlow
2023-12-31,0.964422,0.594397,0.382979,249.769599,6.407592,8.668948,7.696685,0.40827
2022-12-31,0.924234,0.457927,0.250309,223.405503,1.950658,8.581414,5.291582,0.331217
2021-12-31,0.87864,0.398703,0.197805,244.655767,5.187879,11.078788,4.622832,0.380618
2020-12-31,0.982342,0.476009,0.330783,326.21115,2.996894,14.128106,5.634056,0.456445

In [8]:
obj_ibm.LeverageRatios()

           DebtEquityRatio EquityRatio DebtRatio
2023-12-31        2.659877    0.166614  0.443172
2022-12-31        2.461402    0.172457  0.424487
2021-12-31        2.917253    0.143188  0.417717
2020-12-31        3.160072    0.132057  0.417308

In [9]:
obj_ibm.WACC()

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:295: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  D = self.balance_sheet.loc['TotalDebt'][0]
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:283: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'CAPM': capm[0].round(4),
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:284: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'Sharpe': sharpe[0].round(4)
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:302: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  costDebt = np.divide(self.income_stmt.loc['InterestExpense'][0],
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:305: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  tax_rate = np.divide(self.income_stmt.loc['TaxProvision'][0],
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:306: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  self.income_stmt.loc['NetIncome'][0])

  Symbol      WACC
0    IBM  0.081713

In [10]:
obj_ibm.CCC()

                  DIO        DSO        DPO       CCC
2023-12-31  20.441854  38.793788    53.5415  5.694142
2022-12-31  20.234807  39.646188  52.999201  6.881794
2021-12-31  21.781461    41.8438  57.050213  6.575048
2020-12-31   23.17091  43.490889  60.689469  5.972329

In [11]:
obj_ibm.CAPM()

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:283: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'CAPM': capm[0].round(4),
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:284: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'Sharpe': sharpe[0].round(4)

  Symbol    CAPM  Sharpe
0    IBM  0.0988  2.5768

In [12]:
obj_ibm.z_score()

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:176: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_1 = np.divide(self.balance_sheet.loc['CurrentAssets',:][0],
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:177: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  self.balance_sheet.loc['TotalAssets',:][0])
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:179: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_2 = np.divide(self.balance_sheet.loc['RetainedEarnings',:][0],
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:180: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  self.balance_sheet.loc['TotalAssets',:][0])
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:182: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_3 = np.divide(self.income_stmt.loc['EBIT',:][0],
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:183: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  self.balance_sheet.loc['TotalAssets',:][0])
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:185: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_4 = np.divide(self.marketCap, self.balance_sheet.loc['TotalLiabilitiesNetMinorityInterest',:][0])
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:187: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_5 = np.divide(self.income_stmt.loc['TotalRevenue',:][0],
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:188: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  self.balance_sheet.loc['TotalAssets',:][0])

  Symbol  Z Score       Zone
0    IBM    3.645  Safe Zone

In [13]:
obj_ibm.z_score_plot()

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:211: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_1 = np.divide(self.balance_sheet.loc['CurrentAssets',:][0],
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:212: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  self.balance_sheet.loc['TotalAssets',:][0])
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:214: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_2 = np.divide(self.balance_sheet.loc['RetainedEarnings',:][0],
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:215: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  self.balance_sheet.loc['TotalAssets',:][0])
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:217: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_3 = np.divide(self.income_stmt.loc['EBIT',:][0],
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:218: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  self.balance_sheet.loc['TotalAssets',:][0])
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:220: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_4 = np.divide(self.marketCap, self.balance_sheet.loc['TotalLiabilitiesNetMinorityInterest',:][0])
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:222: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_5 = np.divide(self.income_stmt.loc['TotalRevenue',:][0],
/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:223: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  self.balance_sheet.loc['TotalAssets',:][0])

In [14]:
GRUMA = FinRatioAnalysis('GRUMAB.MX', 'yearly')

In [15]:
GRUMA.ReturnRatios()

                 ROE       ROA      ROCE GrossMargin OperatingMargin NetProfit
2023-12-31  0.233342  0.091703  0.186964    0.354855        0.098509  0.065304
2022-12-31  0.222619  0.072771  0.157002    0.353696        0.094136  0.057038
2021-12-31   0.21022  0.078951  0.162291    0.359701        0.105636  0.065351
2020-12-31  0.194417  0.072955  0.177904    0.382455        0.111476  0.058923

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('ROE').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('ROA').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('ROCE').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_3.groupby('GrossMargin').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['ROA'].value_counts()
    for x_label, grp in _df_4.groupby('ROE')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('ROE')
_ = plt.ylabel('ROA')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['ROCE'].value_counts()
    for x_label, grp in _df_5.groupby('ROA')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('ROA')
_ = plt.ylabel('ROCE')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['GrossMargin'].value_counts()
    for x_label, grp in _df_6.groupby('ROCE')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('ROCE')
_ = plt.ylabel('GrossMargin')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['OperatingMargin'].value_counts()
    for x_label, grp in _df_7.groupby('GrossMargin')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('GrossMargin')
_ = plt.ylabel('OperatingMargin')

In [16]:
GRUMA.CCC()

                   DIO        DSO        DPO        CCC
2023-12-31   70.781499  28.763211  32.557015  66.987696
2022-12-31     83.0216  33.797803  38.187033   78.63237
2021-12-31  101.436329  40.910693  46.657164  95.689858
2020-12-31  106.197859  41.308997  48.847302  98.659555

In [17]:
GRUMA.LiquidityRatios()

,CurrentRatios,QuickRatio,CashRatio,DIR,TIE,TIE_CB,CAPEX_OpCash,OpCashFlow
2023-12-31,1.72654,0.756317,0.287354,138.560404,36.257682,41.471931,3.510185,0.608272
2022-12-31,1.895208,0.814475,0.275325,149.29043,31.385738,17.887883,1.007033,0.291233
2021-12-31,1.949872,0.860266,0.311841,148.067932,29.982505,34.435114,1.917443,0.686072
2020-12-31,1.813984,0.973157,0.373237,143.575713,6.050204,7.667717,3.456292,0.780315

In [18]:
GRUMA.z_score()

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:176: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:177: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:179: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:180: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:182: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:183: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:185: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:187: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:188: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

      Symbol  Z Score       Zone
0  GRUMAB.MX   27.464  Safe Zone

In [19]:
SOR = FinRatioAnalysis('SORIANAB.MX', 'yearly')

In [20]:
SOR.ReturnRatios()

                 ROE       ROA      ROCE GrossMargin OperatingMargin NetProfit
2023-12-31  0.063815  0.033142  0.085153    0.227879        0.055224  0.028509
2022-12-31  0.066307  0.034549  0.087827    0.221635        0.057621  0.030231
2021-12-31  0.061263  0.030274  0.086267    0.218838        0.059177  0.027897
2020-12-31  0.054604  0.025894   0.08622    0.217118        0.057522  0.023438

In [ ]:
SOR.EfficiencyRatios()

,AssetTurnover,ReceivableTurnover,InventoryTurnover,FixedAssetTurnover
2022-12-31,1.14187,NaN,4.356746,1.668338
2021-12-31,1.085203,NaN,4.260425,1.596387
2020-12-31,1.10477,191.528049,4.43637,1.60116

In [ ]:
SOR.LeverageRatios()

           DebtEquityRatio EquityRatio DebtRatio
2022-12-31        0.307337    0.521051  0.160138
2021-12-31        0.362939     0.49417  0.179354
2020-12-31        0.436311    0.474208  0.206902

In [ ]:
SOR.CAPM()

        Symbol  CAPM  Sharpe
0  SORIANAB.MX   NaN     NaN

In [21]:
SOR.CCC()

                  DIO       DSO        DPO       CCC
2023-12-31  80.342489  1.933596  78.077109  4.198977
2022-12-31  84.477335   2.04955  82.095367  4.431518
2021-12-31  90.089746  2.193569  87.549527  4.733788
2020-12-31  88.858059  2.168344  86.352569  4.673834

In [22]:
SOR.WACC()

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:295: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:283: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:284: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:302: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:305: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:306: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

        Symbol  WACC
0  SORIANAB.MX   NaN

In [ ]:
SOR.z_score()

        Symbol  Z Score       Zone
0  SORIANAB.MX    2.978  Grey Zone

In [23]:
SOR.z_score_plot()

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:211: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:212: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:214: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:215: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:217: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:218: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:220: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:222: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/usr/local/lib/python3.10/dist-packages/FinRatioAnalysis/FinRatioAnalysis.py:223: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`